goal_app/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show] do
    resources :goals, only: [:new, :create, :edit, :update]
  end

  resources :goals, only: [:destroy]
  
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

goal_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goal_app/app/models/goal.rb
class Goal < ApplicationRecord

  validates :title, :user_id, presence: true

  belongs_to :user

end

goal_app/app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true, uniqueness: true

  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_token
  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def ensure_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_token
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  has_many :goals
end

goal_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in

  def login(user)
    session[:session_token] = user.reset_token
    @current_user = user
  end

  def logged_in
    !!current_user
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user || User.find_by(session_token: session[:session_token])
  end

  def logout
    current_user.reset_token
    session[:session_token] = nil
  end
end

goal_app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
    @user = User.find(params[:user_id])
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = params[:user_id]
    @user = User.find(params[:user_id])

    if @goal.save
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end

  end

  def destroy

  end

  def edit

  end

  def update

  end

  def goal_params
    params.require(:goal).permit(:title)
  end

end

goal_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username and/or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

goal_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goal_app/app/helpers/application_helper.rb
module ApplicationHelper
end

goal_app/app/helpers/goals_helper.rb
module GoalsHelper
end

goal_app/app/helpers/users_helper.rb
module UsersHelper
end

goal_app/app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

goal_app/app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

goal_app/app/views/goals/edit.html.erb
<h1>Goals#edit</h1>
<p>Find me in app/views/goals/edit.html.erb</p>

goal_app/app/views/goals/new.html.erb
<form class="" action="<%= user_goals_url(@user) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="">Title
    <input type="text" name="goal[title]" value="">
  </label>

  <input type="submit" value="Create Goal">
</form>

goal_app/app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

goal_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in %>
      <h2>Welcome, <%= current_user.username %></h2>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="submit" name="" value="Log Out">
      </form>
    <% end %>
    <%= yield %>
  </body>
</html>

goal_app/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

goal_app/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

<label>
  Username
  <input type="text" name="user[username]" value="">
</label>
<label>
  Password
  <input type="text" name="user[password]" value="">
</label>
<input type="submit" name="" value="Create User">
</form>

goal_app/app/views/users/show.html.erb
<% unless @user.goals.empty? %>
  <% @user.goals.each do |goal| %>
    <%= goal.title %>
     <% end %>
<% end %>


<a href="<%= new_user_goal_url(@user) %>">Add Goal</a>